### ISSUE TITLE
Implementar página de busca vazia

### ISSUE THREAD

**Issue by afonso-praca** [vtex-apps/app-store-theme#51]

**Comment by afonso-praca** [comment]
- pelo menos mensagem de não encontrou

**Comment by afonso-praca** [comment]
Quando nenhum item é retornado deve haver unma mensagem de busca vazia

![image](https://user-images.githubusercontent.com/484167/92273775-5e37c200-eec2-11ea-9259-3f2d4d82ab5b.png)

**Comment by lucis** [comment]
Closed by #81
